### ISSUE TITLE
gfs.v16.3.0 Implementation: All missing values in VIIRS radiance bufr

### ISSUE THREAD

**Issue by emilyhcliu** [NOAA-EMC/obsproc#64] opened 2022-08-02 02:14 UTC
We are running gfs.v16.3.0 **real-time** parallel for testing a bug found in NSST.
The start date is 2022061918, and the first analysis is 2022062000.
We noticed that the VIIRS radiances are not assimilated as we expected.
                           
```
                          read_in     keep  assim
o-g 01 rad  npp viirs-m  65887737      0      0    0.0000       0.0000       0.0000       0.0000

o-g 01 rad  j1  viirs-m  71580211      0      0    0.0000       0.0000       0.0000       0.0000
```

The VIIRS bufr file (gdas.t12z.sstvcw.tm00.bufr_d sstviirs) exists, but the observed data (TMBR) were filled with missing values. So, no data passed the read routine.  We have about a week of assimilation results, and all VIIRS data are missing.  

We also ran gfs.v16.3.0 in retrospective mode from 2021101518Z for about three weeks.  TMBR has valid values and VIIRS radiances were assimilated.  

We need help from the ObsProc team to find out the status of the VIIRS data.  Do we expect that the TMBR values in the VIIRS bufr are all missing values?

**Comment by ilianagenkova** [comment] 2022-08-05 17:09
ObsProc confirmed that TMBR mnemonic is missing since 3 June 2022 in the gdas.t12z.sstvcw.tm00.bufr_d sstviirs files. NESDIS has removed Bright Temp from the  _v2.r80_ version of VIIRS SST files (both *.nc and *.bufr)
User request was submited and a meeting was held to discuss restoring the missing BT.

**Comment by ilianagenkova** [comment] 2023-01-31 19:52
Discussion with NESDIS (PAL Sheekela & data provider) lead to reversing the removal of ch. 12,15 and 16  Bright Temp in the gdas.t12z.sstvcw.tm00.bufr_d product.
@emilyhcliu , I am closing this issue. If you have anything to add here, please re-open the issue and tag me in it. Thanks!

**Closed as completed by ilianagenkova** 2023-01-31 19:52 UTC
